/**
 * Names no one can register. Covers impersonation (admin, official, support),
 * system accounts, and app route words in case usernames ever appear outside
 * the /u/ namespace.
 */
const RESERVED = new Set([
  "admin",
  "administrator",
  "moderator",
  "mod",
  "staff",
  "team",
  "official",
  "system",
  "sysadmin",
  "root",
  "support",
  "help",
  "helpdesk",
  "security",
  "artchive",
  "api",
  "bot",
  "null",
  "undefined",
  "anonymous",
  "guest",
  "user",
  "users",
  "test",
  "info",
  "contact",
  "mail",
  "email",
  "postmaster",
  "abuse",
  "webmaster",
  "noreply",
  "no-reply",
  "login",
  "logout",
  "signup",
  "signin",
  "sign-in",
  "sign-up",
  "settings",
  "welcome",
  "explore",
  "search",
  "forgot-password",
  "reset-password",
  "pin",
  "pins",
  "muse",
  "muses",
  "collection",
  "collections",
  "home",
  "about",
  "terms",
  "privacy",
  "status",
]);

/** Lowercase alphanumeric + underscore, 3-30 chars, not reserved. */
export function isUsernameAllowed(username: string): boolean {
  const name = username.toLowerCase();
  if (!/^[a-z0-9_]{3,30}$/.test(name)) return false;
  return !RESERVED.has(name);
}
