/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as WelcomeRouteImport } from './routes/welcome'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppAdminRouteImport } from './routes/_app/admin'
import { Route as AppSavedRouteImport } from './routes/_app/saved'
import { Route as AppSearchRouteImport } from './routes/_app/search'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppUpdatesRouteImport } from './routes/_app/updates'
import { Route as AuthLoginRouteImport } from './routes/_auth.login'
import { Route as AuthSignupRouteImport } from './routes/_auth.signup'
import { Route as ApiCollectRouteImport } from './routes/api/collect'
import { Route as ApiUploadRouteImport } from './routes/api/upload'
import { Route as AppAdminIndexRouteImport } from './routes/_app/admin.index'
import { Route as AppAdminAudienceRouteImport } from './routes/_app/admin.audience'
import { Route as AppAdminContentRouteImport } from './routes/_app/admin.content'
import { Route as AppAdminModerationRouteImport } from './routes/_app/admin.moderation'
import { Route as AppCIdRouteImport } from './routes/_app/c.$id'
import { Route as AppMuseSlugRouteImport } from './routes/_app/muse.$slug'
import { Route as AppPinIdRouteImport } from './routes/_app/pin.$id'
import { Route as AppUUsernameRouteImport } from './routes/_app/u.$username'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const WelcomeRoute = WelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRoute,
} as any)
const AppSavedRoute = AppSavedRouteImport.update({
  id: '/saved',
  path: '/saved',
  getParentRoute: () => AppRoute,
} as any)
const AppSearchRoute = AppSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppUpdatesRoute = AppUpdatesRouteImport.update({
  id: '/updates',
  path: '/updates',
  getParentRoute: () => AppRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => AuthRoute,
} as any)
const ApiCollectRoute = ApiCollectRouteImport.update({
  id: '/api/collect',
  path: '/api/collect',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUploadRoute = ApiUploadRouteImport.update({
  id: '/api/upload',
  path: '/api/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAdminIndexRoute = AppAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminAudienceRoute = AppAdminAudienceRouteImport.update({
  id: '/audience',
  path: '/audience',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminContentRoute = AppAdminContentRouteImport.update({
  id: '/content',
  path: '/content',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminModerationRoute = AppAdminModerationRouteImport.update({
  id: '/moderation',
  path: '/moderation',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppCIdRoute = AppCIdRouteImport.update({
  id: '/c/$id',
  path: '/c/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppMuseSlugRoute = AppMuseSlugRouteImport.update({
  id: '/muse/$slug',
  path: '/muse/$slug',
  getParentRoute: () => AppRoute,
} as any)
const AppPinIdRoute = AppPinIdRouteImport.update({
  id: '/pin/$id',
  path: '/pin/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppUUsernameRoute = AppUUsernameRouteImport.update({
  id: '/u/$username',
  path: '/u/$username',
  getParentRoute: () => AppRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/welcome': typeof WelcomeRoute
  '/admin': typeof AppAdminRouteWithChildren
  '/saved': typeof AppSavedRoute
  '/search': typeof AppSearchRoute
  '/settings': typeof AppSettingsRoute
  '/updates': typeof AppUpdatesRoute
  '/login': typeof AuthLoginRoute
  '/signup': typeof AuthSignupRoute
  '/api/collect': typeof ApiCollectRoute
  '/api/upload': typeof ApiUploadRoute
  '/admin/audience': typeof AppAdminAudienceRoute
  '/admin/content': typeof AppAdminContentRoute
  '/admin/moderation': typeof AppAdminModerationRoute
  '/c/$id': typeof AppCIdRoute
  '/muse/$slug': typeof AppMuseSlugRoute
  '/pin/$id': typeof AppPinIdRoute
  '/u/$username': typeof AppUUsernameRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/admin/': typeof AppAdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof AppIndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/welcome': typeof WelcomeRoute
  '/saved': typeof AppSavedRoute
  '/search': typeof AppSearchRoute
  '/settings': typeof AppSettingsRoute
  '/updates': typeof AppUpdatesRoute
  '/login': typeof AuthLoginRoute
  '/signup': typeof AuthSignupRoute
  '/api/collect': typeof ApiCollectRoute
  '/api/upload': typeof ApiUploadRoute
  '/admin/audience': typeof AppAdminAudienceRoute
  '/admin/content': typeof AppAdminContentRoute
  '/admin/moderation': typeof AppAdminModerationRoute
  '/c/$id': typeof AppCIdRoute
  '/muse/$slug': typeof AppMuseSlugRoute
  '/pin/$id': typeof AppPinIdRoute
  '/u/$username': typeof AppUUsernameRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/admin': typeof AppAdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_auth': typeof AuthRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/welcome': typeof WelcomeRoute
  '/_app/admin': typeof AppAdminRouteWithChildren
  '/_app/saved': typeof AppSavedRoute
  '/_app/search': typeof AppSearchRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/updates': typeof AppUpdatesRoute
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/signup': typeof AuthSignupRoute
  '/api/collect': typeof ApiCollectRoute
  '/api/upload': typeof ApiUploadRoute
  '/_app/': typeof AppIndexRoute
  '/_app/admin/audience': typeof AppAdminAudienceRoute
  '/_app/admin/content': typeof AppAdminContentRoute
  '/_app/admin/moderation': typeof AppAdminModerationRoute
  '/_app/c/$id': typeof AppCIdRoute
  '/_app/muse/$slug': typeof AppMuseSlugRoute
  '/_app/pin/$id': typeof AppPinIdRoute
  '/_app/u/$username': typeof AppUUsernameRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/_app/admin/': typeof AppAdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/reset-password'
    | '/welcome'
    | '/admin'
    | '/saved'
    | '/search'
    | '/settings'
    | '/updates'
    | '/login'
    | '/signup'
    | '/api/collect'
    | '/api/upload'
    | '/admin/audience'
    | '/admin/content'
    | '/admin/moderation'
    | '/c/$id'
    | '/muse/$slug'
    | '/pin/$id'
    | '/u/$username'
    | '/api/auth/$'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/reset-password'
    | '/welcome'
    | '/saved'
    | '/search'
    | '/settings'
    | '/updates'
    | '/login'
    | '/signup'
    | '/api/collect'
    | '/api/upload'
    | '/admin/audience'
    | '/admin/content'
    | '/admin/moderation'
    | '/c/$id'
    | '/muse/$slug'
    | '/pin/$id'
    | '/u/$username'
    | '/api/auth/$'
    | '/admin'
  id:
    | '__root__'
    | '/_app'
    | '/_auth'
    | '/forgot-password'
    | '/reset-password'
    | '/welcome'
    | '/_app/admin'
    | '/_app/saved'
    | '/_app/search'
    | '/_app/settings'
    | '/_app/updates'
    | '/_auth/login'
    | '/_auth/signup'
    | '/api/collect'
    | '/api/upload'
    | '/_app/'
    | '/_app/admin/audience'
    | '/_app/admin/content'
    | '/_app/admin/moderation'
    | '/_app/c/$id'
    | '/_app/muse/$slug'
    | '/_app/pin/$id'
    | '/_app/u/$username'
    | '/api/auth/$'
    | '/_app/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  WelcomeRoute: typeof WelcomeRoute
  ApiCollectRoute: typeof ApiCollectRoute
  ApiUploadRoute: typeof ApiUploadRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/welcome': {
      id: '/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof WelcomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin': {
      id: '/_app/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/saved': {
      id: '/_app/saved'
      path: '/saved'
      fullPath: '/saved'
      preLoaderRoute: typeof AppSavedRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/search': {
      id: '/_app/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof AppSearchRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/updates': {
      id: '/_app/updates'
      path: '/updates'
      fullPath: '/updates'
      preLoaderRoute: typeof AppUpdatesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/signup': {
      id: '/_auth/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof AuthRoute
    }
    '/api/collect': {
      id: '/api/collect'
      path: '/api/collect'
      fullPath: '/api/collect'
      preLoaderRoute: typeof ApiCollectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/upload': {
      id: '/api/upload'
      path: '/api/upload'
      fullPath: '/api/upload'
      preLoaderRoute: typeof ApiUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/admin/': {
      id: '/_app/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AppAdminIndexRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/admin/audience': {
      id: '/_app/admin/audience'
      path: '/audience'
      fullPath: '/admin/audience'
      preLoaderRoute: typeof AppAdminAudienceRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/admin/content': {
      id: '/_app/admin/content'
      path: '/content'
      fullPath: '/admin/content'
      preLoaderRoute: typeof AppAdminContentRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/admin/moderation': {
      id: '/_app/admin/moderation'
      path: '/moderation'
      fullPath: '/admin/moderation'
      preLoaderRoute: typeof AppAdminModerationRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/c/$id': {
      id: '/_app/c/$id'
      path: '/c/$id'
      fullPath: '/c/$id'
      preLoaderRoute: typeof AppCIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/muse/$slug': {
      id: '/_app/muse/$slug'
      path: '/muse/$slug'
      fullPath: '/muse/$slug'
      preLoaderRoute: typeof AppMuseSlugRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/pin/$id': {
      id: '/_app/pin/$id'
      path: '/pin/$id'
      fullPath: '/pin/$id'
      preLoaderRoute: typeof AppPinIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/u/$username': {
      id: '/_app/u/$username'
      path: '/u/$username'
      fullPath: '/u/$username'
      preLoaderRoute: typeof AppUUsernameRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppAdminRouteChildren {
  AppAdminAudienceRoute: typeof AppAdminAudienceRoute
  AppAdminContentRoute: typeof AppAdminContentRoute
  AppAdminModerationRoute: typeof AppAdminModerationRoute
  AppAdminIndexRoute: typeof AppAdminIndexRoute
}

const AppAdminRouteChildren: AppAdminRouteChildren = {
  AppAdminAudienceRoute: AppAdminAudienceRoute,
  AppAdminContentRoute: AppAdminContentRoute,
  AppAdminModerationRoute: AppAdminModerationRoute,
  AppAdminIndexRoute: AppAdminIndexRoute,
}

const AppAdminRouteWithChildren = AppAdminRoute._addFileChildren(
  AppAdminRouteChildren,
)

interface AppRouteChildren {
  AppAdminRoute: typeof AppAdminRouteWithChildren
  AppSavedRoute: typeof AppSavedRoute
  AppSearchRoute: typeof AppSearchRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppUpdatesRoute: typeof AppUpdatesRoute
  AppIndexRoute: typeof AppIndexRoute
  AppCIdRoute: typeof AppCIdRoute
  AppMuseSlugRoute: typeof AppMuseSlugRoute
  AppPinIdRoute: typeof AppPinIdRoute
  AppUUsernameRoute: typeof AppUUsernameRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAdminRoute: AppAdminRouteWithChildren,
  AppSavedRoute: AppSavedRoute,
  AppSearchRoute: AppSearchRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppUpdatesRoute: AppUpdatesRoute,
  AppIndexRoute: AppIndexRoute,
  AppCIdRoute: AppCIdRoute,
  AppMuseSlugRoute: AppMuseSlugRoute,
  AppPinIdRoute: AppPinIdRoute,
  AppUUsernameRoute: AppUUsernameRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface AuthRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
  AuthSignupRoute: typeof AuthSignupRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
  AuthSignupRoute: AuthSignupRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  WelcomeRoute: WelcomeRoute,
  ApiCollectRoute: ApiCollectRoute,
  ApiUploadRoute: ApiUploadRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
